Update push workflow

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -14,21 +14,17 @@ name: Push CD
 # - CUSTOM_CR_NAMESPACE
 # - IMAGES_PREFIX
 
+# Helper scripts:
+# - ./.github/workflows/scripts/set_github_env.sh
+# - ./.github/workflows/scripts/set_registry_credentials.sh
+
 on:
 
-  # Run on push on production branches
+  # Run on pushes to primary branches
   push:
     branches:
-      # Production
-      - main
-    paths:
-      # CI files
-      - '.github/workflows/push.yml'
-      - 'docker-compose.yml'
-      - '.env'
-      # Application files
-      - 'chown-command.sh'
-      - 'Dockerfile'
+      # Primary branches
+      - main # Production
 
   # Run on manual triggers
   workflow_dispatch:
@@ -37,7 +33,7 @@ on:
         description: 'Deployment environment (e.g. prod, staging)'
         type: string
 
-# Set default GITHUB_TOKEN permissions for the workflow
+# Set GITHUB_TOKEN permissions for the workflow
 permissions:
   contents: read
 
@@ -48,9 +44,9 @@ concurrency:
 
 # Set environment variables for the workflow
 env:
-  DHCR_ENABLED: ${{ vars.DHCR_ENABLED == 'true' || (!vars.DHCR_ENABLED && vars.DHCR_USERNAME != '') }}
+  DHCR_ENABLED: ${{ vars.DHCR_ENABLED == 'true' }}
   GHCR_ENABLED: ${{ vars.GHCR_ENABLED == 'true' }}
-  CUSTOM_CR_ENABLED: ${{ vars.CUSTOM_CR_ENABLED == 'true' || (!vars.CUSTOM_CR_ENABLED && vars.CUSTOM_CR_URL != '') }}
+  CUSTOM_CR_ENABLED: ${{ vars.CUSTOM_CR_ENABLED == 'true' }}
   IMAGES_PREFIX: ${{ vars.IMAGES_PREFIX }}
 
 jobs:
@@ -59,18 +55,25 @@ jobs:
   push:
     name: Build & Push
     runs-on: ubuntu-latest
-    timeout-minutes: 15
+    timeout-minutes: 20
 
     # Set GITHUB_TOKEN permissions for the job
     permissions:
+      contents: read
       packages: write
+
+    # Set environment variables for the job
+    env:
+      IMAGES_SUFFIX: ''
+      SERVICE_DIR: .
+      BUILD_CONTEXTS: ''
 
     steps:
 
       # Initialization steps
 
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
       # Preparation steps
 
@@ -80,6 +83,9 @@ jobs:
           DEPLOY_ENV: ${{ github.event.inputs.deploy_env }}
         run: |
           # Set DEPLOY_ENV environment variable
+
+          # Load helper scripts
+          . ./.github/workflows/scripts/set_github_env.sh
 
           if [ -n "${DEPLOY_ENV}" ]; then
             # Sanitize DEPLOY_ENV value:
@@ -99,19 +105,17 @@ jobs:
             DEPLOY_ENV="STAGING"
           fi
 
-          echo "Set DEPLOY_ENV to '${DEPLOY_ENV}'"
-          echo 'DEPLOY_ENV<<GITHUB_ENV_EOF' >> $GITHUB_ENV
-          echo "${DEPLOY_ENV}" >> $GITHUB_ENV
-          echo 'GITHUB_ENV_EOF' >> $GITHUB_ENV
+          set_github_env 'DEPLOY_ENV' "${DEPLOY_ENV}" non-optional non-secret verbose
 
       - name: Set Docker Hub registry credentials
-        if: env.DHCR_ENABLED == 'true'
+        if: env.DHCR_ENABLED == 'true' || vars.DHCR_USERNAME != ''
         env:
           REGISTRY_URL: docker.io
           REGISTRY_USERNAME: ${{ vars.DHCR_USERNAME }}
           REGISTRY_TOKEN: ${{ secrets.DHCR_TOKEN }}
           REGISTRY_NAMESPACE: ${{ vars.DHCR_USERNAME }}
           IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
+          IMAGES_SUFFIX: ${{ env.IMAGES_SUFFIX }}
           REPOSITORY_OWNER: ${{ github.repository_owner }}
           REPOSITORY_PATH: ${{ github.repository }}
         run: |
@@ -123,7 +127,7 @@ jobs:
 
           set_registry_credentials \
             'DHCR_URL' \
-            'DHCR_IMAGES_PREFIX' \
+            'DHCR_IMAGES_NAME' \
             'DHCR_USERNAME' \
             'DHCR_TOKEN'
 
@@ -135,6 +139,7 @@ jobs:
           REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REGISTRY_NAMESPACE: ${{ github.repository_owner }}
           IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
+          IMAGES_SUFFIX: ${{ env.IMAGES_SUFFIX }}
           REPOSITORY_OWNER: ${{ github.repository_owner }}
           REPOSITORY_PATH: ${{ github.repository }}
         run: |
@@ -146,7 +151,7 @@ jobs:
 
           set_registry_credentials \
             'GHCR_URL' \
-            'GHCR_IMAGES_PREFIX' \
+            'GHCR_IMAGES_NAME' \
             'GHCR_USERNAME' \
             'GHCR_TOKEN'
 
@@ -158,6 +163,7 @@ jobs:
           REGISTRY_TOKEN: ${{ secrets.CUSTOM_CR_TOKEN }}
           REGISTRY_NAMESPACE: ${{ vars.CUSTOM_CR_NAMESPACE }}
           IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
+          IMAGES_SUFFIX: ${{ env.IMAGES_SUFFIX }}
           REPOSITORY_OWNER: ${{ github.repository_owner }}
           REPOSITORY_PATH: ${{ github.repository }}
         run: |
@@ -169,7 +175,7 @@ jobs:
 
           set_registry_credentials \
             'CUSTOM_CR_URL' \
-            'CUSTOM_CR_IMAGES_PREFIX' \
+            'CUSTOM_CR_IMAGES_NAME' \
             'CUSTOM_CR_USERNAME' \
             'CUSTOM_CR_TOKEN'
 
@@ -177,7 +183,7 @@ jobs:
 
       - name: Login to Docker Hub registry
         if: env.DHCR_URL
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.DHCR_URL }}
           username: ${{ env.DHCR_USERNAME }}
@@ -185,7 +191,7 @@ jobs:
 
       - name: Login to GitHub registry
         if: env.GHCR_URL
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.GHCR_URL }}
           username: ${{ env.GHCR_USERNAME }}
@@ -193,72 +199,94 @@ jobs:
 
       - name: Login to custom registry
         if: env.CUSTOM_CR_URL
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.CUSTOM_CR_URL }}
           username: ${{ env.CUSTOM_CR_USERNAME }}
           password: ${{ env.CUSTOM_CR_TOKEN }}
 
       - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+        uses: docker/setup-qemu-action@v4
+        with:
+          platforms: arm64
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v4
 
       - name: Set Docker image tags
         env:
           DEPLOY_ENV: ${{ env.DEPLOY_ENV }}
-          DHCR_IMAGES_PREFIX: ${{ env.DHCR_IMAGES_PREFIX }}
-          GHCR_IMAGES_PREFIX: ${{ env.GHCR_IMAGES_PREFIX }}
-          CUSTOM_CR_IMAGES_PREFIX: ${{ env.CUSTOM_CR_IMAGES_PREFIX }}
+          DHCR_ENABLED: ${{ env.DHCR_ENABLED }}
+          DHCR_IMAGES_NAME: ${{ env.DHCR_IMAGES_NAME }}
+          GHCR_ENABLED: ${{ env.GHCR_ENABLED }}
+          GHCR_IMAGES_NAME: ${{ env.GHCR_IMAGES_NAME }}
+          CUSTOM_CR_ENABLED: ${{ env.CUSTOM_CR_ENABLED }}
+          CUSTOM_CR_IMAGES_NAME: ${{ env.CUSTOM_CR_IMAGES_NAME }}
           GITHUB_SHA: ${{ github.sha }}
         run: |
           # Set Docker image tags
 
+          # Load helper scripts
+          . ./.github/workflows/scripts/set_github_env.sh
+
           IMAGE_TAGS=''
 
           # Include image tag for Docker Hub registry
-          if [ -n "${DHCR_IMAGES_PREFIX}" ]; then
-            IMAGE_TAGS="${IMAGE_TAGS},${DHCR_IMAGES_PREFIX}:${GITHUB_SHA}"
+          if [ "${DHCR_ENABLED}" = "true" ] && [ -n "${DHCR_IMAGES_NAME}" ]; then
+            echo 'Generate Docker Hub image tag (commit SHA)'
+            IMAGE_TAGS="${IMAGE_TAGS},${DHCR_IMAGES_NAME}:${GITHUB_SHA}"
             if [ "${DEPLOY_ENV}" = "PROD" ]; then
-              IMAGE_TAGS="${IMAGE_TAGS},${DHCR_IMAGES_PREFIX}:latest"
+              echo 'Generate Docker Hub image tag (latest)'
+              IMAGE_TAGS="${IMAGE_TAGS},${DHCR_IMAGES_NAME}:latest"
             fi
           fi
 
           # Include image tag for GitHub registry
-          if [ -n "${GHCR_IMAGES_PREFIX}" ]; then
-            IMAGE_TAGS="${IMAGE_TAGS},${GHCR_IMAGES_PREFIX}:${GITHUB_SHA}"
+          if [ "${GHCR_ENABLED}" = "true" ] && [ -n "${GHCR_IMAGES_NAME}" ]; then
+            echo 'Generate GitHub registry image tag (commit SHA)'
+            IMAGE_TAGS="${IMAGE_TAGS},${GHCR_IMAGES_NAME}:${GITHUB_SHA}"
             if [ "${DEPLOY_ENV}" = "PROD" ]; then
-              IMAGE_TAGS="${IMAGE_TAGS},${GHCR_IMAGES_PREFIX}:latest"
+              echo 'Generate GitHub registry image tag (latest)'
+              IMAGE_TAGS="${IMAGE_TAGS},${GHCR_IMAGES_NAME}:latest"
             fi
           fi
 
           # Include image tag for custom registry
-          if [ -n "${CUSTOM_CR_IMAGES_PREFIX}" ]; then
-            IMAGE_TAGS="${IMAGE_TAGS},${CUSTOM_CR_IMAGES_PREFIX}:${GITHUB_SHA}"
+          if [ "${CUSTOM_CR_ENABLED}" = "true" ] && [ -n "${CUSTOM_CR_IMAGES_NAME}" ]; then
+            echo 'Generate custom registry image tag (commit SHA)'
+            IMAGE_TAGS="${IMAGE_TAGS},${CUSTOM_CR_IMAGES_NAME}:${GITHUB_SHA}"
             if [ "${DEPLOY_ENV}" = "PROD" ]; then
-              IMAGE_TAGS="${IMAGE_TAGS},${CUSTOM_CR_IMAGES_PREFIX}:latest"
+              echo 'Generate custom registry image tag (latest)'
+              IMAGE_TAGS="${IMAGE_TAGS},${CUSTOM_CR_IMAGES_NAME}:latest"
             fi
           fi
 
           # Remove leading comma
-          IMAGE_TAGS="${IMAGE_TAGS#,}"
+          IMAGE_TAGS="$(echo "${IMAGE_TAGS}" | sed 's/^,//')"
 
-          echo 'Set Docker image tags'
-          echo 'IMAGE_TAGS<<GITHUB_ENV_EOF' >> $GITHUB_ENV
-          echo "${IMAGE_TAGS}" >> $GITHUB_ENV
-          echo 'GITHUB_ENV_EOF' >> $GITHUB_ENV
+          if [ -z "${IMAGE_TAGS}" ]; then
+            echo 'Error: No Docker image tags generated.' >&2
+            exit 1
+          fi
+
+          set_github_env 'IMAGE_TAGS' "${IMAGE_TAGS}" non-optional non-secret verbose
 
       - name: Build & push Docker image
-        uses: docker/build-push-action@v6
+        uses: docker/build-push-action@v7
         env:
           DOCKER_BUILD_CHECKS_ANNOTATIONS: true
           DOCKER_BUILD_SUMMARY: true
           DOCKER_BUILD_RECORD_UPLOAD: false
         with:
           tags: ${{ env.IMAGE_TAGS }}
-          context: .
-          file: ./Dockerfile
+          file: ${{ env.SERVICE_DIR }}/Dockerfile
+          context: ${{ env.SERVICE_DIR }}
+          build-contexts: ${{ env.BUILD_CONTEXTS }}
           target: app_prod
+          build-args: |
+            PORT=8080
+            BUILD_CHECK=false
           platforms: linux/amd64,linux/arm64
           push: true
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
